In [35]:
# predict salary using multiple linear regression model
import pandas as pd
import numpy as np
from sklearn import linear_model

In [36]:
#loading the dataset
df=pd.read_csv(r"C:\Users\91705\Documents\datasets\predict salary.csv")

In [45]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [49]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [50]:
# the dataset contains some messy and noisy data , so we need to clean it
# to give accurate predections about salary

# column experence should contain numeric data because we have to deal with numeric data so lets do it ist
# convert word to number
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)

In [51]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [58]:
# fill median in test_score colunm cell
import math
median=math.floor(df['test_score(out of 10)'].mean())


In [59]:
median

7

In [61]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median)

In [62]:
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [76]:
#creating a model object 
reg=linear_model.LinearRegression()

In [77]:
#training the model
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']].values, df['salary($)'])

LinearRegression()

In [80]:
#prediction
reg.predict([[0,8.0,9]])

array([52090.46734071])

In [83]:
reg.predict([[0,0,2]])

array([19287.61657943])

In [86]:
# HOW IT WORKS ACTUALLY
#salary=m1*experience+m2*test_score(out of 10) +m3*interview_score(out of 10)+b

In [87]:
# getting intercept (b)
reg.intercept_

14992.65144669314

In [88]:
#getting coefficient (m1,m2,m3)
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [89]:
salary=2922.26901502*0+2221.30909959*8+2147.48256637*9+14992.65144669314

In [90]:
#predicted salary
salary

52090.46734074314