In [7]:
# implementation of multiple linear regression model
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [8]:
# get dataset
df=pd.read_csv(r"C:\Users\91705\Desktop\machine learning\multiple linear regression model\dataset1.csv")

In [9]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [10]:
# we need to preprocess the dataset beacause there exists noise so we need to clean this noise
# we are going to fill NaN with median of bedrooms column it is good assumption
br_median =df.bedrooms.median()
br_median

3.5

In [11]:
# we need integer so we will import maths lib and user floor function
import math
br_median=math.floor(br_median)

In [12]:
br_median

3

In [13]:
#now fill this br_median into NaN cell in dataset
df.bedrooms = df.bedrooms.fillna(br_median)

In [14]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [16]:
# creating model object 
mlr = linear_model.LinearRegression()

In [17]:
# training the model 
mlr.fit(df[['area','bedrooms','age']].values,df.price)

LinearRegression()

In [21]:
# predicting price for (3000 sqr ft area, 3 bedrooms, 4 yrs old)
mlr.predict([[3000,3,4]])

array([690100.])

In [22]:
# predicting price for (2500 sqr ft area, 4 bedrooms, 5 yrs old)
mlr.predict([[2500,4,5]])

array([588625.])

In [23]:
# seeing how it actually works
# price = m*area + m*bedrooms + m*age + b

# getting intercept
mlr.intercept_

383724.9999999998

In [24]:
#getting coefficients
mlr.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [27]:
#putting vaules into above equation
price=137.25*2500+(-26025.)*4+-6825.*5+383724.9999999998

In [28]:
price

588624.9999999998